// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5byENul3BdHAPCk0z-9pRNaOHnBm460',
    appId: '1:187419406357:web:f91bdc90dbb39d8f5d1e1c',
    messagingSenderId: '187419406357',
    projectId: 'sponjobtest',
    authDomain: 'sponjobtest.firebaseapp.com',
    storageBucket: 'sponjobtest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IRmXP4IpSLBMKOlxE3CwtTZvCeelGhM',
    appId: '1:187419406357:android:1055cb4dd888a1ea5d1e1c',
    messagingSenderId: '187419406357',
    projectId: 'sponjobtest',
    storageBucket: 'sponjobtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgWO7kv93TgyiClxzNlnErfnialfIqAFk',
    appId: '1:187419406357:ios:7d2f76405bbbd5ca5d1e1c',
    messagingSenderId: '187419406357',
    projectId: 'sponjobtest',
    storageBucket: 'sponjobtest.appspot.com',
    androidClientId: '187419406357-cm4e92psbsrsi8gq1dp4j2ahvcv9d433.apps.googleusercontent.com',
    iosClientId: '187419406357-j5c70sm6hv041fbtg8a3eng7i9896959.apps.googleusercontent.com',
    iosBundleId: 'com.example.sponjobsadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgWO7kv93TgyiClxzNlnErfnialfIqAFk',
    appId: '1:187419406357:ios:7d2f76405bbbd5ca5d1e1c',
    messagingSenderId: '187419406357',
    projectId: 'sponjobtest',
    storageBucket: 'sponjobtest.appspot.com',
    androidClientId: '187419406357-cm4e92psbsrsi8gq1dp4j2ahvcv9d433.apps.googleusercontent.com',
    iosClientId: '187419406357-j5c70sm6hv041fbtg8a3eng7i9896959.apps.googleusercontent.com',
    iosBundleId: 'com.example.sponjobsadmin',
  );
}
