// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3-b2JCUyr5UHdZPly3DluIGIen_pYI8',
    appId: '1:651189680177:web:27ed242ed238f47cc07d10',
    messagingSenderId: '651189680177',
    projectId: 'sponjob-97f63',
    authDomain: 'sponjob-97f63.firebaseapp.com',
    storageBucket: 'sponjob-97f63.appspot.com',
    measurementId: 'G-47PJGENFFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw36_iRs7-W4f-X1q9BUCwAO_hqisd6l0',
    appId: '1:651189680177:android:921da4c4bfcbe4b2c07d10',
    messagingSenderId: '651189680177',
    projectId: 'sponjob-97f63',
    storageBucket: 'sponjob-97f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqwK52UtHbg7tUP64LKIO6WeMtMdzKXE',
    appId: '1:651189680177:ios:3768b11b3e95c54cc07d10',
    messagingSenderId: '651189680177',
    projectId: 'sponjob-97f63',
    storageBucket: 'sponjob-97f63.appspot.com',
    androidClientId: '651189680177-61r35on4k99q0ig3rlfeom381hkt7poe.apps.googleusercontent.com',
    iosClientId: '651189680177-udpmkj0okcjongkh4tbmlkokkgdbhkn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sponjobsadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnqwK52UtHbg7tUP64LKIO6WeMtMdzKXE',
    appId: '1:651189680177:ios:3768b11b3e95c54cc07d10',
    messagingSenderId: '651189680177',
    projectId: 'sponjob-97f63',
    storageBucket: 'sponjob-97f63.appspot.com',
    androidClientId: '651189680177-61r35on4k99q0ig3rlfeom381hkt7poe.apps.googleusercontent.com',
    iosClientId: '651189680177-udpmkj0okcjongkh4tbmlkokkgdbhkn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sponjobsadmin',
  );
}
